FROM python:3.9-slim

WORKDIR /usr/src/app

COPY ftp_server.py .

RUN pip install flask && \
    mkdir -p /usr/src/app/images && \
    mkdir -p /usr/src/app/temp_uploads

CMD ["python", "ftp_server.py"]