services:
  researchproject:
    image: researchproject
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms: 
        - linux/amd64
        - linux/arm64
    # volumes:
    #   - type: bind
    #     source: ${IMAGE_STORAGE_PATH}
    #     target: /usr/src/app/images
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      # - fileserver

  # fileserver:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.fileserver
  #   volumes:
  #     - type: bind
  #       source: ${IMAGE_STORAGE_PATH}
  #       target: /usr/src/app/images
  #   environment:
  #     UPLOAD_FOLDER: /usr/src/app/images
  #   ports:
  #     - "5000:5000"